name: Linter
on: push

jobs:
  lua_lint:
    runs-on: ubuntu-latest
    name: GLua Linter
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2
      - name: Linting
        id: action-glua-lint
        uses: TASSIA710/action-glua-lint@v1.1.2
        with:
          lint_unusedParameters: false
          lint_unusedLoopVars: false
          failOnWarning: true
